const branches = [
['ТОО «ТЖС-Актобе»','г. Актобе, ул. 8-Наурыз, 7','8 (7132) 97-63-33','tzhs_aktobe@mail.ru','Водопроводные сети — 65,51 км; скважины — 15; водонапорные башни — 11; ВНС — 3; резервуары — 9; канализационные сети — 4,214 км; КНС — 2; тепловые сети — 7,39 км; котельные — 3; котельные на техобслуживании — 1.'],
['ТОО «ТЖС-Алматы»','г. Алматы, ул. Шацкого, 11','8 (7272) 96-32-25','temir_jolsu@bk.ru','Водопроводные сети — 59,862 км; скважины — 34; водонапорные башни — 17; ВНС — 29; резервуары — 16; канализационные сети — 4,381 км; тепловые сети — 13,75 км; котельные — 1; электрокотлы — 2; котельные на техобслуживании — 5.'],
['ТОО «ТЖС-Арыс»','г. Арыс, ул. Вокзал Маңы, 4а','8 (72540) 5-32-25','moldur_88@mail.ru','Тепловые сети — 3,246 км; котельные — 2.'],
['ТОО «ТЖС-Аягоз»','г. Аягоз, ул. Н. Макеев, 2д','8 (72237) 5-18-93','tzhs.ayagoz.1@mail.ru','Водопроводные сети — 40,99 км; скважины — 16; водонапорные башни — 7; ВНС — 13; резервуары — 2; канализационные сети — 17 км; КНС — 3; тепловые сети — 2,054 км; котельные — 2.'],
['ТОО «ТЖС-Караганда»','г. Караганда, ул. Карпатская, строение 19В','8 (7212) 93-24-61','tjskaraganda@mail.ru','Водопроводные сети — 60,117 км; скважины — 14; водонапорные башни — 3; ВНС — 16; резервуары — 2; канализационные сети — 8,741 км; КНС — 2; тепловые сети — 1,611 км; котельные — 8; электрокотлы — 16; котельные на техобслуживании — 6.'],
['ТОО «ТЖС-Кокшетау»','г. Кокшетау, ул. Шалкар, дом 1А','8 (7162) 29-22-29','tootemirzolsukoksetau@gmail.com','Водопроводные сети — 7,29 км; водонапорные башни — 1; ВНС — 1; канализационные сети — 0,83 км; тепловые сети — 3,033 км; котельные — 3.'],
['ТОО «ТЖС-Костанай»','г. Костанай, проспект Аль-Фараби, дом 158/5','8 (7142) 90-15-80','tjs-kostanay@mail.ru','Водопроводные сети — 45,023 км; скважины — 8; водонапорные башни — 5; ВНС — 5; резервуары — 1; канализационные сети — 2,1 км; КНС — 1; тепловые сети — 2,807 км; котельные — 6; электрокотлы — 2; котельные на техобслуживании — 3.'],
['ТОО «ТЖС-Кызыл-Орда»','г. Кызылорда, пер. Адама Мекебаева, 45','8 (7242) 29-33-33','tjs_k-orda@mail.ru','Водопроводные сети — 88,6 км; скважины — 37; водонапорные башни — 17; ВНС — 3; резервуары — 4; тепловые сети — 0,656 км; котельные — 4.'],
['ТОО «ТЖС-Маңғыстау»','с. Мангистау, промышленная зона 1, строение 38','8 (7292) 46-57-41','tzhs-mangystau@mail.ru','Водопроводные сети — 26,081 км; скважины — 3; водонапорные башни — 3; ВНС — 4; резервуары — 8; канализационные сети — 14,65 км; КНС — 3; тепловые сети — 4,826 км; котельные — 2; котельные на техобслуживании — 9.'],
['ТОО «ТЖС-Павлодар»','г. Павлодар, промышленная зона Центральная, строение 2242','8 (7182) 37-35-35','tzspavlodar@gmail.com','Водопроводные сети — 166,08 км; скважины — 18; водонапорные башни — 9; ВНС — 13; резервуары — 7; канализационные сети — 55,67 км; КНС — 22; тепловые сети — 7,42 км; котельные — 4; электрокотлы — 4.']
];

const kk = {
  skip:'Мазмұнға өту', tagline:'Теміржолға арналған су мен жылу', menu:'Мәзір', menuAria:'Мәзірді ашу', navAria:'Негізгі навигация', nav:['Компания туралы','Қызмет бағыты','Еншілес ұйымдар','Басшылық'],
  heroTitle:'Сенімді жабдықтау<br>темір жол ырғағында', heroText:'«ҚТЖ» ҰК» АҚ инфрақұрылымын сумен және жылумен жабдықтаудың, ағынды суларды бұрудың үздіксіз циклін технологиялық қамтамасыз ету.', aboutButton:'Компания туралы', heroCaption:'Қазақстан темір жолының су және жылумен жабдықтау объектілері',
  stats:['қызмет көрсетілетін станция<br>мен разъезд','ел өңірлеріндегі<br>еншілес ұйым','2023–2025 жылдары<br>жөнделген объект'],
  about:['Компания туралы','Тұрақты қозғалыстың<br>инженерлік негізі','«Теміржолсу» АҚ — «ҚТЖ» ҰК» АҚ көлік инфрақұрылымын сумен және жылумен жабдықтаудың, ағынды суларды бұрудың үздіксіз циклін технологиялық қамтамасыз ететін негізгі оператор.','Компания өңірлік құзыреттер мен бірыңғай өндірістік стандарттарды біріктіре отырып, теміржолдың коммуналдық инфрақұрылымын пайдалану мен техникалық қызмет көрсетуді қамтамасыз етеді.'],
  services:['Қызмет бағыттары','Инфрақұрылымға арналған<br>кешенді қызметтер','Сумен жабдықтау','Су құбыр желілерін, ұңғымаларды, сорғы станциялары мен резервуарларды, соның ішінде тасымалданатын сумен жабдықтауды пайдалану.','Ағынды суларды төгу','Кәріз желілері мен кәріз сорғы станцияларына техникалық қызмет көрсету.','Жылумен жабдықтау','Теміржол инфрақұрылымы объектілеріндегі қазандықтарды, электр қазандықтарын және жылу желілерін пайдалану.','Сервис және жөндеу','ЦЖС объектілеріне, ғимараттар мен құрылыстарға ағымдағы жөндеу және техникалық қызмет көрсету.'],
  history:['Тарих','Құрылуы және дамуы','24 желтоқсанда Қоғам «ҚТЖ» ҰК» ЖАҚ Директорлар кеңесінің шешімімен «Желдорводотеплоснабжение» ААҚ-ны бөліп шығару нысанында қайта ұйымдастыру арқылы құрылды.','Қазақстан Республикасы Үкіметінің № 1006 қаулысымен бекітілген Көлік инфрақұрылымын дамыту бағдарламасы шеңберінде Қоғам қайта ұйымдастырылды.','Қоғамға «Теміржолжылу» АҚ және «Желдорводотеплоснабжение» ААҚ қосылып, қызмет саласы кеңейді.','Бүгін','Компания теміржол инфрақұрылымын коммуналдық және пайдалану қызметтерімен қамтамасыз ету бағытында дамуын жалғастыруда.'],
  assets:['Инфрақұрылым','Өндірістік қуаттар','Компания меншікті активтерімен 128 пунктті қамтамасыз етеді, сондай-ақ «ҚТЖ» ҰК» АҚ филиалының объектілеріне тағы 278 теміржол пунктінде қызмет көрсетеді.','Сумен жабдықтау','меншікті су құбыры желілері','Жерасты көздері','артезиан ұңғымалары','Сақтау объектілері','су мұнаралары','Су беру','су сорғы станциялары','Жылумен жабдықтау','қазандықтар','Су бұру','кәріз желілері','Жылу желілері','меншікті жылу желілері'],
  subsidiaries:['Өңірлік желі','Еншілес ұйымдар','10 еншілес ұйым табиғи монополиялардың дербес субъектілері болып табылады және өңірлердегі инфрақұрылымның жұмысын қамтамасыз етеді.'],
  projects:['Кешенді мердігерлік қызметтер','906 объект — «ҚТЖ» ҰК» АҚ инфрақұрылымын<br>ағымдағы жөндеу','Кешенді мердігерлік қызметтер шеңберінде теміржол инфрақұрылымы объектілеріне ағымдағы жөндеу жүргізіледі. 2023–2025 жылдары «ҚТЖ» ҰК» АҚ-ның 906 объектісінде, оның ішінде локомотив бригадаларының 26 демалыс үйінде ағымдағы жөндеу жұмыстары орындалды.','Ақтөбедегі әкімшілік ғимаратты жөндеу нәтижесі','Атыраудағы әкімшілік ғимаратты жөндеу нәтижесі','Шортанды станциясы ЭЦ посты объектісін ағымдағы жөндеу'],
  leadership:['Корпоративтік басқару','Басшылық','Бас директор<br><small>(Басқарма төрағасы)</small>','Өндіріс жөніндегі бас директордың орынбасары','Экономика және қаржы жөніндегі бас директордың орынбасары','Бас инженер','Бас бухгалтер','Директорлар кеңесі','Садырқұлов Р.Б. — Директорлар кеңесінің төрағасы','Рахымбеков А.Н. — Директорлар кеңесінің мүшесі','Әбілсейітова С.К. — Тәуелсіз директор, Директорлар кеңесінің мүшесі'],
  footer:['Қазақстан Республикасы теміржол инфрақұрылымын сумен және жылумен жабдықтауды технологиялық қамтамасыз ету.','Навигация','Компания туралы','Қызмет бағыты','Еншілес ұйымдар','Басшылық','«Теміржолсу» АҚ байланыстары','Телефон:','E-mail:','Жоғарыға ↑'], labels:['Мекенжай:','Телефон:','Техникалық қуаттар:','Толығырақ +','Жинау −']
};

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const original = new Map();
function capture(selector, html=false){ $$(selector).forEach(n=>{ if(!original.has(n)) original.set(n, html?n.innerHTML:n.textContent); }); }
function put(selector, values, html=false){ $$(selector).forEach((n,i)=>{ if(!original.has(n)) original.set(n, html?n.innerHTML:n.textContent); const value=Array.isArray(values)?values[i]:values; n[html?'innerHTML':'textContent']=value; }); }
function restore(){ original.forEach((value,node)=>{ if(node.matches('.hero-content h1,#about h2,#services h2,.projects h2,.leaders .leader-copy p,.stats-grid span,.asset-grid span')) node.innerHTML=value; else node.textContent=value; }); document.documentElement.lang='ru'; document.title='АО «Теміржолсу»'; }
function kkText(value){ return value.replaceAll('ТОО','ЖШС').replace('Актобе','Ақтөбе').replace('Аягоз','Аягөз').replace('Караганда','Қарағанды').replace('Кокшетау','Көкшетау').replace('Костанай','Қостанай').replace('Кызыл-Орда','Қызылорда').replace('г. ','').replace('с. ','ауылы, ').replace('ул. ','көшесі, ').replace('проспект ','даңғылы, ').replace('пер. ','тұйық көшесі, ').replace('дом ','үй ').replace('строение ','ғимарат ').replace('промышленная зона','өнеркәсіптік аймақ').replaceAll('Водопроводные сети','Су құбыры желілері').replaceAll('скважины','ұңғымалар').replaceAll('водонапорные башни','су мұнаралары').replaceAll('ВНС','су сорғы станциялары').replaceAll('резервуары','резервуарлар').replaceAll('канализационные сети','кәріз желілері').replaceAll('КНС','кәріз сорғы станциялары').replaceAll('тепловые сети','жылу желілері').replaceAll('котельные на техобслуживании','техникалық қызмет көрсетудегі қазандықтар').replaceAll('котельные','қазандықтар').replaceAll('электрокотлы','электр қазандықтары'); }
function renderBranches(language){ const labels=language==='kk'?kk.labels:['Адрес:','Телефон:','Технические мощности:','Подробнее +','Свернуть −']; $('#subsidiaryList').innerHTML=branches.map((row,i)=>{const [name,address,phone,email,capacity]=language==='kk'?row.map((x,j)=>j===2||j===3?x:kkText(x)):row; return `<article class="subsidiary"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${name}</h3><span class="place">${address}</span></div><span class="place">${phone}</span><button aria-label="${labels[3].replace(' +','')}: ${name}" aria-expanded="false">+</button><div class="details"><p><strong>${labels[0]}</strong> ${address}<br><strong>${labels[1]}</strong> ${phone}<br><strong>E-mail:</strong> <a href="mailto:${email}">${email}</a></p><p class="capacity"><strong>${labels[2]}</strong><br>${capacity}</p></div></article>`;}).join(''); }
function apply(language){ if(language==='ru'){restore(); renderBranches('ru');} else { document.documentElement.lang='kk'; document.title='«Теміржолсу» АҚ'; put('.skip',kk.skip); put('.brand small',kk.tagline); put('.menu-btn',kk.menu); put('.navline nav a',kk.nav); put('.hero-content h1',kk.heroTitle,true); put('.hero-content > p:not(.eyebrow)',kk.heroText); put('.hero-content .button',`${kk.aboutButton} <span>→</span>`,true); put('.hero-caption',kk.heroCaption); put('.stats-grid span',kk.stats,true); put('#about .eyebrow',kk.about[0]); put('#about h2',kk.about[1],true); put('#about .lead p',kk.about.slice(2)); put('#services .eyebrow',kk.services[0]); put('#services h2',kk.services[1],true); put('#services .services-grid h3',[kk.services[2],kk.services[4],kk.services[6],kk.services[8]]); put('#services .services-grid p',[kk.services[3],kk.services[5],kk.services[7],kk.services[9]]); put('.history .eyebrow',kk.history[0]); put('.history h2',kk.history[1]); put('.history li p',[kk.history[2],kk.history[3],kk.history[4],kk.history[6]]); put('.history li:last-child span',kk.history[5]); put('.assets .eyebrow',kk.assets[0]); put('.assets h2',kk.assets[1]); put('.assets .section-heading p',kk.assets[2]); put('.asset-grid em',[kk.assets[3],kk.assets[5],kk.assets[7],kk.assets[9],kk.assets[11],kk.assets[13],kk.assets[15]]); put('.asset-grid span',[kk.assets[4],kk.assets[6],kk.assets[8],kk.assets[10],kk.assets[12],kk.assets[14],kk.assets[16]],true); put('#subsidiaries .eyebrow',kk.subsidiaries[0]); put('#subsidiaries h2',kk.subsidiaries[1]); put('#subsidiaries .section-heading p',kk.subsidiaries[2]); put('.projects .eyebrow',kk.projects[0]); put('.projects h2',kk.projects[1],true); put('.project-lead',kk.projects[2]); put('#leadership .eyebrow',kk.leadership[0]); put('#leadership h2',kk.leadership[1]); put('.leaders .leader-copy p',kk.leadership.slice(2,7),true); put('.board h3',kk.leadership[7]); put('.board p',kk.leadership.slice(8)); put('.footer-brand small',kk.tagline); put('.footer-grid > div:first-child > p',kk.footer[0]); put('.footer-grid > div:nth-child(2) h3',kk.footer[1]); put('.footer-grid > div:nth-child(2) a',kk.footer.slice(2,6)); put('.footer-grid > div:nth-child(3) h3',kk.footer[6]); const fp=$$('.footer-grid > div:nth-child(3) p'); if(fp[0])fp[0].childNodes[0].nodeValue=`${kk.footer[7]} `;if(fp[1])fp[1].childNodes[0].nodeValue=`${kk.footer[8]} `;put('.up',kk.footer[9]); $$('.project-gallery img').forEach((n,i)=>n.alt=kk.projects[i+3]); $('.hero-image').alt=kk.heroCaption; renderBranches('kk'); }
  $$('.language-switcher button').forEach(b=>{const active=b.dataset.language===language;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}); localStorage.setItem('temirzholsu-language',language); }
function syncMeta(language){const kz=language==='kk';const title=kz?'«Теміржолсу» АҚ':'АО «Теміржолсу»';const hero=kz?'Қазақстан темір жолының су және жылумен жабдықтау объектілері':'Объекты водо- и теплоснабжения железной дороги Казахстана';const alts=kz?['Ақтөбедегі әкімшілік ғимаратты жөндеу нәтижесі','Атыраудағы әкімшілік ғимаратты жөндеу нәтижесі','Шортанды станциясы ЭЦ посты объектісін ағымдағы жөндеу']:['Результат ремонта административного здания в Актобе','Результат ремонта административного здания в Атырау','Текущий ремонт объекта поста ЭЦ станции Шортанды'];document.title=title;$('.brand').setAttribute('aria-label',kz?'Теміржолсу АҚ, басты бет':'АО Теміржолсу, главная');$('.brand img').setAttribute('alt',kz?'Теміржолсу АҚ логотипі':'Логотип АО Теміржолсу');$('.menu-btn').setAttribute('aria-label',kz?'Мәзірді ашу':'Открыть меню');$('.navline nav').setAttribute('aria-label',kz?'Негізгі навигация':'Основная навигация');$('.language-switcher').setAttribute('aria-label',kz?'Тілді таңдау':'Выбор языка');$('.hero-image').setAttribute('alt',hero);$$('.project-gallery img').forEach((n,i)=>n.setAttribute('alt',alts[i]));}
function syncFooterLabels(language){const labels=language==='kk'?['Телефон:','E-mail:']:['Телефон:','E-mail:'];const p=$$('.footer-grid > div:nth-child(3) p');if(p[0])p[0].childNodes[0].nodeValue=`${labels[0]} `;if(p[1])p[1].childNodes[0].nodeValue=`${labels[1]} `;}
$('#subsidiaryList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const open=b.closest('.subsidiary').classList.toggle('open');b.textContent=open?'−':'+';b.setAttribute('aria-expanded',String(open));}); $('.menu-btn').addEventListener('click',e=>{const open=$('.navline').classList.toggle('nav-open');e.currentTarget.setAttribute('aria-expanded',String(open));}); $$('.language-switcher button').forEach(b=>b.addEventListener('click',()=>{apply(b.dataset.language);syncMeta(b.dataset.language);syncFooterLabels(b.dataset.language);})); const savedLanguage=localStorage.getItem('temirzholsu-language')==='kk'?'kk':'ru'; apply(savedLanguage);syncMeta(savedLanguage);syncFooterLabels(savedLanguage);
